### PR TITLE
Abstract fetcher

### PR DESCRIPTION
**Pull request by hantrungkien**
- refactor network: abstract fetcher
- modified AXrLottieDrawable.setCustomEndFrame() same as Telegram latest version
- add OkHttpFetcher & Lottie Initialize to the example
- clean code base

### CODE REVIEW

**Comment by hantrungkien** [comment]
@Aghajari Hope to see your review soon!

**Comment by Aghajari** [comment]
Well done @hantrungkien ,
i saw your codes, i'll use them for sure. 
+ i've added a simple OkHttpNetworkFetcher for now..

**Comment by hantrungkien** [comment]
@Aghajari thanks but could you please help me to resolve this issue https://github.com/Aghajari/AXrLottie/issues/4

**Comment by Aghajari** [comment]
Done.

**Pull request closed without merging**
